services:
  - type: web
    name: nike-ph-dashboard
    env: python
    plan: free
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: cd webapp && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
